version: '3.9'
services:
  java:
    image: eclipse-temurin:11
    volumes:
      - .:/embulk
    working_dir: /embulk
  gradle:
    image: gradle:8-jdk8
    volumes:
      - .:/embulk
    working_dir: /embulk
